{% set name = "huey" %}
{% set version = "2.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/huey-{{ version }}.tar.gz
  sha256: 089fc72b97fd26a513f15b09925c56fad6abe4a699a1f0e902170b37e85163c7

build:
  noarch: python
  entry_points:
    - huey_consumer = huey.bin.huey_consumer:consumer_main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
  run_constrained:
    - redis-py >=3.0.0

test:
  imports:
    - huey
  commands:
    - pip check
    - huey_consumer --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/coleifer/huey/
  summary: huey, a little task queue
  license: MIT
  license_file: LICENSE
  doc_url: https://huey.readthedocs.io

extra:
  recipe-maintainers:
    - kwilcox
    - synapticarbors
