{% set name = "huey" %}
{% set version = "1.11.0" %}
{% set sha256 = "a0b78c94b6c316f6a7d1cb508659bb4b66aed9ef01fc1c76f1c13999261a7011" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/coleifer/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - huey_consumer = huey.bin.huey_consumer:consumer_main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - peewee
    - redis-py

test:
  imports:
    - huey

  commands:
    - huey_consumer --help

about:
  home: https://github.com/coleifer/huey
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A little task queue for python
  doc_url: http://huey.readthedocs.org/
  dev_url: https://github.com/coleifer/huey

extra:
  recipe-maintainers:
    - kwilcox
