{% set version = "2.3.2" %}

package:
  name: huey
  version: {{ version }}

source:
  url: https://github.com/coleifer/huey/archive/{{ version }}.tar.gz
  sha256: ed9a283ef0e6eb3d94176e68278a0d7c1fcca786642c7b4ed306de02220ba157

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - huey_consumer = huey.bin.huey_consumer:consumer_main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - redis-py

test:
  imports:
    - huey

  commands:
    - huey_consumer --help

about:
  home: https://github.com/coleifer/huey
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A little task queue for python
  doc_url: http://huey.readthedocs.org/
  dev_url: https://github.com/coleifer/huey

extra:
  recipe-maintainers:
    - kwilcox
