{% set version = "2.1.3" %}

package:
  name: huey
  version: {{ version }}

source:
  url: https://github.com/coleifer/huey/archive/{{ version }}.tar.gz
  sha256: 139637fe3eca75732329f59efb0e30fbc3f70e0ed6237ca3dc045d437583c269

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - huey_consumer = huey.bin.huey_consumer:consumer_main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - redis-py

test:
  requires:
    - python {{ python_min }}
  imports:
    - huey

  commands:
    - huey_consumer --help

about:
  home: https://github.com/coleifer/huey
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A little task queue for python
  doc_url: http://huey.readthedocs.org/
  dev_url: https://github.com/coleifer/huey

extra:
  recipe-maintainers:
    - kwilcox
