{% set version = "2.2.0" %}

package:
  name: huey
  version: {{ version }}

source:
  url: https://github.com/coleifer/huey/archive/{{ version }}.tar.gz
  sha256: 521fda6f2ae507c53e9e5fcddde45b20c467ea510c977122907596e263af07bd

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - huey_consumer = huey.bin.huey_consumer:consumer_main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - redis-py

test:
  imports:
    - huey

  commands:
    - huey_consumer --help

about:
  home: https://github.com/coleifer/huey
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A little task queue for python
  doc_url: http://huey.readthedocs.org/
  dev_url: https://github.com/coleifer/huey

extra:
  recipe-maintainers:
    - kwilcox
