travis:
  secure:
    BINSTAR_TOKEN: m6Osg7JVB606MsqvQY3w1tO48K2QQiqonLmGsGuhuB9QAATNCYOR/kNHRkgrhD/+aYvaWI17yJSqKXjc0A1m7VDkqpW96eNTWTc5z9uROxPeBbwiFfxvVKFPj/MmfKLDUQiKQWEdzzWlGWehQX97My9cj5O1emQHcUxblxgzJBTrzvrVvgM1rG9Mr4zm8aOQHGCv0vvd7Y9FoSHam4b/RyovRZAO8bwfBDRRqgeOsZ5gCC8UiHeEcFEPUZ0p/TFN/nrfeb0ePrX8MF+BsZE0MTt9xabFHFOmM86hzQsj+fhtMERLmyFSIfHy7jdP11WoY+FUEWEtoQJ+UYce1tiCZvcnCNiSkcwlwsyl1Ci7nYb50SoGhrgEdrgQ+VbVdCy4zUStMNy5xJoZkxqFctILv13JRuYOuCHc94vsFZsqL/sVNnqc5e+vaRe9x90YpewCOjZYE7l1Jt5HywVP7Ed+Mb3m4ZDKTcxYZ/igzyIsaxcI+XpU930xyUy+Zixp1gVNmzy8FQlQFvwPiyYh6Rbg9WWo8LFIXunzrhdudTdTfGxyxf7daptzYaX7E62SxNV10Inc55gOg+aQ1D1315bY+iNJ7QlL/op166LBeg9hpbWFgUtvD1K0FsJi0gD76wgem762UHrW+tH+69rgP+z2nQqb/Bciw8HBgHWSmsPa2Ys=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
