travis:
  secure:
    BINSTAR_TOKEN: YpPpqQ7e6aMzQYHYSHo5L1jTnIgguS7smKLDFpqI0fTkgOM6raTjFfWvDLNC9IYJLhP3Doq29FJ9bmUoKAxk1b0kcOQAWSwU/Oyomw9ueSCPm1N6amu0hcaTxak+TWMVlGqsTcmuejSNoRaTXFdKFWeCi5OIG1clf8bZ4ZrXaxr/frpt5jOYNVg0BT30+ZwY0jJme3XXSzwhJVy5FYcZEsMJuBOStI6IODFhzJEcfh8OpqZOTxuNipVHbIicil7RTsDKwF2vhZ3OkyUyKJ8r1sknWeNIEbRc/IxKTrAZwkyb/N4qPpRjICn02BfiS0gOVTblTPjQN9k3660b5njrJR/1GtJamqz2/wRvNDLDMu36H8f+G/I/KnkIkxBZnDCzmCudXv30GnHz4eFw6wrHHhqXTC5XjZ+aEezl2wRMKXswGfcbc5XMqEMQ6feEdC3gvCSs5a8tCF8V7+7ptOBQmt2ZImI9o70y5PNnkuC0ptwRH7zP/bYCU4xhmcOJAP3a+yCwY+kFAra8XJu53wjcX5u2C1VRRymFQyEI3LNC2gA63l42z9JdnwwmfnLsYF0gdjiK7ziDxCNLSVGRpHN876NfoQkIlupnSLZty9L+aj2S1V7pbG41MqMRhWMWEfLczc/IT0D9TdkXYDVNmNnagG0NKBKLZYHe9Of9CP0RiAY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
